/**
 * diagramRegeneration.ts
 *
 * Strategy pattern entry point for converting a hand-drawn diagram into a
 * regenerated, machine-rendered version.
 *
 * Two strategies are wired up today:
 *  - mermaid:   produces editable Mermaid syntax. Best for flowcharts,
 *               state machines, sequence diagrams, mind maps, and trees.
 *  - gpt-image: produces a PNG generated by gpt-image-1 from a vision-model
 *               description of the cropped drawing. Best for freeform
 *               sketches and geometry that Mermaid cannot represent.
 *
 * The 'auto' setting routes by the detected diagram type. The caller does
 * not need to know which strategy ran — it just inspects `usedStrategy` on
 * the result and reads the right field.
 */

import type { DetectedDiagramBbox } from "./diagramDetection";
import { generateMermaidFromImage } from "./mermaidGeneration";
import { generateGptImageFromDiagram } from "./gptImageGeneration";
import type { DiagramRegenerationMethod, HandwritingProvider } from "./settings";

export interface RegenerationContext {
	croppedImage: File;
	bbox: DetectedDiagramBbox;
	apiKey: string;
	provider: HandwritingProvider;
	method: DiagramRegenerationMethod;
	/**
	 * OpenAI key for gpt-image-1. May equal `apiKey` when the user is on
	 * OpenAI for everything; required only if the chosen strategy ends up
	 * being gpt-image.
	 */
	openaiApiKey?: string;
}

export type RegeneratedDiagram =
	| {
			usedStrategy: "mermaid";
			/** Plain Mermaid syntax. Caller wraps in ```mermaid block. */
			mermaidCode: string;
	  }
	| {
			usedStrategy: "gpt-image";
			/** PNG bytes ready to be written to the vault. */
			pngBytes: Uint8Array;
			/** Description used as the gpt-image-1 prompt. Useful for debugging. */
			usedDescription: string;
	  };

/**
 * Pick a strategy and return a regenerated representation of the diagram.
 */
export async function regenerateDiagram(
	ctx: RegenerationContext,
): Promise<RegeneratedDiagram> {
	const strategy = pickStrategy(ctx);

	if (strategy === "mermaid") {
		return await runMermaid(ctx);
	}
	return await runGptImage(ctx);
}

function pickStrategy(ctx: RegenerationContext): "mermaid" | "gpt-image" {
	if (ctx.method === "mermaid") return "mermaid";
	if (ctx.method === "gpt-image") return "gpt-image";

	// 'auto': route by diagram type. Anything that has a clean structural
	// representation goes to Mermaid; freeform sketches and geometry go to
	// gpt-image.
	const type = ctx.bbox.type.toLowerCase();
	const mermaidFriendly = new Set([
		"flowchart",
		"state_machine",
		"sequence_diagram",
		"mind_map",
		"tree",
		"class_diagram",
	]);
	if (mermaidFriendly.has(type)) return "mermaid";
	return "gpt-image";
}

async function runMermaid(ctx: RegenerationContext): Promise<RegeneratedDiagram> {
	const result = await generateMermaidFromImage(
		{
			croppedImage: ctx.croppedImage,
			description: ctx.bbox.description,
			suggestedType: ctx.bbox.type,
		},
		{ apiKey: ctx.apiKey, provider: ctx.provider },
	);
	return { usedStrategy: "mermaid", mermaidCode: result.mermaidCode };
}

async function runGptImage(ctx: RegenerationContext): Promise<RegeneratedDiagram> {
	const openaiKey = ctx.openaiApiKey ?? (ctx.provider === "openai" ? ctx.apiKey : "");
	if (!openaiKey) {
		throw new Error(
			"GPT-image regeneration requires an OpenAI API key. Configure your API key as an OpenAI key, or set the regeneration method to Mermaid.",
		);
	}

	const result = await generateGptImageFromDiagram(
		{
			croppedImage: ctx.croppedImage,
			description: ctx.bbox.description,
			suggestedType: ctx.bbox.type,
		},
		{
			visionApiKey: ctx.apiKey,
			visionProvider: ctx.provider,
			openaiApiKey: openaiKey,
		},
	);

	return {
		usedStrategy: "gpt-image",
		pngBytes: result.pngBytes,
		usedDescription: result.usedDescription,
	};
}